-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

-- Applications and session
hl.bind("SUPER + Q", hl.dsp.window.close(), { description = "Close window" })
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"), { description = "Open Dolphin" })
hl.bind("SUPER + R", hl.dsp.exec_cmd("wofi --show drun"), { description = "Open Wofi" })
hl.bind("SUPER + ALT + L", hl.dsp.exec_cmd("/home/phirios/.local/bin/hypr-dms-lock"), { description = "Lock screen" })
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'), { description = "Copy screenshot region" })
hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"), { description = "Copy screenshot" })
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating window" })
hl.bind("CTRL + ALT + RETURN", hl.dsp.window.fullscreen(), { description = "Toggle fullscreen" })
hl.bind("CTRL + SUPER + RETURN", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle maximize" })
hl.bind("SUPER + SHIFT + M", hl.dsp.exit(), { description = "Exit Hyprland" })
hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("ghostty"), { description = "Open Ghostty" })
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "Toggle Spotlight" })
hl.bind("SUPER + SHIFT + slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"), { description = "Show shortcuts" })
hl.bind("SUPER + Print", hl.dsp.exec_cmd('grim "$HOME/Pictures/Screenshots/hypr-$(date +\'%Y%m%d-%H%M%S\').png"'), { description = "Save screenshot" })

-- DankMaterialShell panels
hl.bind("ALT + SPACE", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { description = "Toggle Spotlight bar" })
hl.bind("CTRL + ALT + SPACE", hl.dsp.exec_cmd("/home/phirios/.local/bin/hypr-emoji-toggle"), { description = "Toggle emoji picker" })
hl.bind("SUPER + ALT + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "Clipboard manager" })
hl.bind("SUPER + ALT + M", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"), { description = "Task manager" })
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"), { description = "Task manager" })
hl.bind("SUPER + ALT + comma", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"), { description = "DMS settings" })
hl.bind("SUPER + X", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "Power menu" })
hl.bind("SUPER + Y", hl.dsp.exec_cmd("dms ipc call dash toggle wallpaper"), { description = "Browse wallpapers" })
hl.bind("SUPER + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"), { description = "Notification center" })
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("dms ipc call notepad toggle"), { description = "Notepad" })
hl.bind("SUPER + C", hl.dsp.exec_cmd("dms ipc call control-center toggle"), { description = "Control center" })
hl.bind("SUPER + A", hl.dsp.exec_cmd("dms ipc call dmsAgent toggle"), { description = "AI Agent chat" })
hl.bind("SUPER + O", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"), { description = "Window overview" })
hl.bind("SUPER + Tab", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"), { description = "Window overview" })

-- Focus and move windows
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }), { description = "Focus left" })
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }), { description = "Focus down" })
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }), { description = "Focus up" })
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }), { description = "Focus right" })
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "left" }), { description = "Move window left" })
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "down" }), { description = "Move window down" })
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "up" }), { description = "Move window up" })
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "right" }), { description = "Move window right" })
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Drag window" })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize window" })

-- Workspaces
hl.bind("SUPER + CTRL + I", hl.dsp.exec_cmd("/home/phirios/.local/bin/hypr-next-empty-workspace"), { description = "Workspace after last occupied workspace" })
hl.bind("SUPER + CTRL + SHIFT + I", hl.dsp.exec_cmd("/home/phirios/.local/bin/hypr-next-empty-workspace move"), { description = "Move window to workspace after last occupied workspace" })
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }), { description = "Workspace 1" })
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }), { description = "Workspace 2" })
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }), { description = "Workspace 3" })
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }), { description = "Workspace 4" })
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }), { description = "Workspace 5" })
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }), { description = "Workspace 6" })
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }), { description = "Workspace 7" })
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }), { description = "Workspace 8" })
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }), { description = "Workspace 9" })
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }), { description = "Workspace 10" })
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }), { description = "Move to workspace 1" })
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }), { description = "Move to workspace 2" })
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }), { description = "Move to workspace 3" })
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }), { description = "Move to workspace 4" })
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }), { description = "Move to workspace 5" })
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }), { description = "Move to workspace 6" })
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }), { description = "Move to workspace 7" })
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }), { description = "Move to workspace 8" })
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }), { description = "Move to workspace 9" })
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }), { description = "Move to workspace 10" })
hl.bind("SUPER + U", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })
hl.bind("SUPER + I", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind("SUPER + SHIFT + U", hl.dsp.window.move({ workspace = "e-1" }), { description = "Move to previous workspace" })
hl.bind("SUPER + SHIFT + I", hl.dsp.window.move({ workspace = "e+1" }), { description = "Move to next workspace" })
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace" })
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace" })

-- Media keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true, description = "Volume down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, description = "Mute audio" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, description = "Mute microphone" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, description = "Next track" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Play or pause" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Play or pause" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, description = "Previous track" })

-- Quick translation popup.
hl.bind("SUPER + T", hl.dsp.exec_cmd("/home/phirios/.local/bin/hypr-translate-popup"), { description = "Translate selected or copied text" })
